### ISSUE TITLE
Lots of "In FUN(newX[, i], ...) : no non-missing arguments to min; returning Inf" warning but no errors

### ISSUE THREAD

**Issue by Deleetdk** [alexkowa/VIM#3]
Often when I use irmi() I get a number of these warnings, but there does not appear to be problems with the input data or the outputted data.

Initial data by matrixplot()
![irmi_initial](https://cloud.githubusercontent.com/assets/6759913/7481566/27b447c8-f371-11e4-9642-a6c7e323cc15.png)

After
![irmi_after](https://cloud.githubusercontent.com/assets/6759913/7481572/32abfb76-f371-11e4-9559-b5eae0b2a14b.png)

The dataset is [this](https://osf.io/t2h9c/files/), which is part of a yet to be released project.

Run this code to reproduce:

```
#S factor
s.data = subset(names.df, select=c("no.job","own.place","married",
                                   "conviction", "income",
                                   "age"))

#missing data
if (F){ #run manually when needed
  matrixplot2(s.data)
  matrixplot(s.data)
  miss.table(s.data)
  miss.hist(s.data)
  ggsave("figures/missing_histogram.png")
}

#impute data
s.data = s.data[miss.case(s.data)<=2,] #subset to cases with 0 or 1 NA
s.data = irmi(s.data) #impute data
```

**Comment by matthias-da** [comment]
Is it because you have NaN's in names.csv instead of NA's? Please try that.
Otherwise, there could be some warnings from nnet or other functions used. 
In any case, your example is not reproducible, I missed miss.case(), for example.

Best,
Matthias

P.S.:
Please cite this
http://link.springer.com/article/10.1007%2Fs11634-011-0102-y

instead of 
Templ, M., Alfons, A., Kowarik, A., & Prantner, B. (2015, February 19). VIM: Visualization and Imputation of Missing Values. CRAN. Retrieved from http://cran.r-project.org/web/packages/VIM/index.html

**Comment by Deleetdk** [comment]
No NaNs, only NAs.

Sorry, miss.case() is from [here](https://github.com/Deleetdk/psych2).

**Comment by matthias-da** [comment]
I still see NaN in names.csv but it should be NA.

**Comment by alexkowa** [comment]
With the code below, which is your example made reproducible!? I cannot reproduce any warnings with the Github-Version of the package.
```
require(VIM)
source("https://raw.githubusercontent.com/Deleetdk/psych2/master/psych2.R")
names.df <- read.csv("https://osf.io/xf8py/?action=download&version=1")
#S factor
s.data = subset(names.df, select=c("no.job","own.place","married",
				"conviction", "income",
				"age"))

#missing data
if (F){ #run manually when needed
	matrixplot2(s.data)
	matrixplot(s.data)
	miss.table(s.data)
	miss.hist(s.data)
	ggsave("figures/missing_histogram.png")
}

#impute data
s.data = s.data[miss.case(s.data)<=2,] #subset to cases with 0 or 1 NA
s.data = irmi(s.data) #impute data
```
