### ISSUE TITLE
irmi fails with data_frame (dplyr)

### ISSUE THREAD

**Issue by Deleetdk** [alexkowa/VIM#6]
`irmi` fails when given a data_frame:

```
> library(VIM)
> library(dplyr)
> test_data = data_frame(a = c(1, 2, 3, NA, 5), b = c(2, 1, NA, 5, 5), c = c(NA, 2, 1, 4, 3))
> cor(test_data, use = "pairwise")
          a         b         c
a 1.0000000 0.8846154 0.6546537
b 0.8846154 1.0000000 0.8660254
c 0.6546537 0.8660254 1.0000000
> VIM::irmi(test_data)
Error in gowerD(don_dist_var, imp_dist_var, weights = weightsx, numericalX,  : 
  (list) object cannot be coerced to type 'double'
> VIM::irmi(as.data.frame(test_data))
Time difference of 0.01601601 secs
```

Works fine when one uses regular data.frames. Note that data_frames *are* data.frames too, just have more classes, so `class()` tests generally fail. Use `inherits()`.

**Comment by alexkowa** [comment]
I added a test file to the tests for the package where it is checked if a data_frame gives the same result as a data.frame (see below or in the source cde itself).
@Deleetdk please check again with the current package version from github
`# irmi should work on data_frame
# 
# Author: Alexander Kowarik
###############################################################################
# sourceD("/Users/alex/git/VIM/R/")

library(VIM)
library(dplyr)
test_data = data_frame(a = c(1, 2, 3, NA, 5), b = c(2, 1, NA, 5, 5), c = c(NA, 2, 1, 4, 3))
identical(as.data.frame(irmi(test_data,noise=FALSE)),irmi(as.data.frame(test_data),noise=FALSE))
identical(as.data.frame(kNN(test_data,addRandom=FALSE)),kNN(as.data.frame(test_data),addRandom=FALSE))
identical(as.data.frame(hotdeck(test_data,ord_var="a")),hotdeck(as.data.frame(test_data),ord_var="a"))

`

**Comment by Deleetdk** [comment]
Works for me.
