### ISSUE TITLE
Support for ordered factors?

### ISSUE THREAD

**Issue by Deleetdk** [alexkowa/VIM#7]
Currently, `VIM::irmi` throws an error if one attempts to impute a data.frame with ordered factors. Given that such data are pretty common, this was surprising to me. I could of course convert these to either ordinary factors (and lose the order) or to integers (and get bias depending on the distribution of values). 

Are there plans to support ordered factors?

**Comment by alexkowa** [comment]
Probably, the error occurs only if there are missing values in the ordered factor, since there is no regression model defined for these variables?
Something like ordinal logistic regression should probably be used?

**Comment by Deleetdk** [comment]
Yes, ordinal logistic regression should be used or some similar approach. I could convert the data to numerical and then impute, and convert back to discrete by rounding, but that's cumbersome.
